name: "Validate dependencies"
description: "Validate dependencies"
runs:
  using: "composite"
  steps:
    - name: Clean and cache setup
      uses: ./.github/actions/cache

    - name: Update Lockfile
      shell: bash
      run: yarn install --mode=update-lockfile

    - name: Install dependencies
      shell: bash
      run: yarn install --mode=skip-build

    - name: Check dependencies
      run: yarn npm audit --all --recursive --environment production --severity moderate
      shell: bash
